### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by uborfly** [QtExcel/Qxlnt#11]
Build HelloQXlnt in sourecode.
Environment:QtCreator4.0.3,Qt5.6.3 MinGW32,compiler MinGW4.9.2 32bit,system windows10
![image](https://user-images.githubusercontent.com/29224392/122360951-652f4d00-cf89-11eb-9d4b-d125eb7dbd53.png)
Looks like the overload function is missing

**Comment by j2doll** [comment]
Dear @uborfly 

:one: C++14 or higher version is required.
 * Use gcc 6.1 or higher version.  https://gcc.gnu.org/projects/cxx-status.html#cxx14
  
  * Check your gcc version. `g++ --version`
 
:two: Use new version of Qt. https://github.com/QtExcel/Qxlnt/blob/master/BuildEnv.md

**Comment by uborfly** [comment]
@j2doll Thanks foryour reply, I tried to compile in linux with gcc 7.5 and Qt 5.11.3, it passed and can be used normally,
