### ISSUE TITLE
build error with Qt 6.1.2 Windows 10

### ISSUE THREAD

**Issue by EinRainerZufall** [QtExcel/Qxlnt#13]
![Screenshot 2021-08-07 225936](https://user-images.githubusercontent.com/77112619/128613855-76ab7169-2b6f-4492-afd7-230e83747195.jpeg)
![Screenshot 2021-08-07 230638](https://user-images.githubusercontent.com/77112619/128613861-e25237a1-6866-488a-b587-baeda315b296.jpeg)

**Comment by j2doll** [comment]
Dear @EinRainerZufall 

Can you please post some testable code? 
(Pull request to https://github.com/JayTwoLab/qxlnt-issues-13)

Maybe me or others can help.

**Comment by EinRainerZufall** [comment]
Sure
Im also new to QT so maybe im doing something wrong

and thanks for the help

**Comment by EinRainerZufall** [comment]
Dear @j2doll 

Is there a tutorial on how to use Qxlnt in a project somewhere, because I think I'm doing something wrong because I haven't been using QT that long?

**Comment by j2doll** [comment]
If you are unfamiliar with Qt, I recommend that you use xlnt. https://github.com/tfussell/xlnt
xlnt uses only C++ standard functions.
 It doesn't use Qt at all.

**Comment by EinRainerZufall** [comment]
ok i found my bug i used MinGW when i switched to MSVC it worked
