### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by anamod** [QtExcel/Qxlnt#18]
Hi! 
I was looking throught your library and testing some formula and found some trouble with SUMIF.
I triy it like this -> `ws.cell("C3").value("=SOMMA.SE($A$1:$A$10;""">0)"");` but it's obviously giving me error beacuse of the apostrophes

Can u pls explain it to me pls?
Thanks

**Comment by j2doll** [comment]
I think I can not help you with that part. 
I guess you'll have to look for help on the xlnt site. https://github.com/tfussell/xlnt
